// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SmartLibrary.Data;
using System;

namespace SmartLibrary.Data.Migrations
{
    [DbContext(typeof(SmartLibraryContext))]
    partial class SmartLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartLibrary.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberId");

                    b.Property<string>("Tilte");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("SmartLibrary.Domain.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("SmartLibrary.Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Memebers");
                });

            modelBuilder.Entity("SmartLibrary.Domain.MemberCompetition", b =>
                {
                    b.Property<int>("MemberId");

                    b.Property<int>("CompetitionId");

                    b.HasKey("MemberId", "CompetitionId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("MemberCompetition");
                });

            modelBuilder.Entity("SmartLibrary.Domain.MemberIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberId");

                    b.Property<string>("RealName");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("MemberIdentity");
                });

            modelBuilder.Entity("SmartLibrary.Domain.Book", b =>
                {
                    b.HasOne("SmartLibrary.Domain.Member", "Member")
                        .WithMany("Books")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartLibrary.Domain.MemberCompetition", b =>
                {
                    b.HasOne("SmartLibrary.Domain.Competition")
                        .WithMany("Competitions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartLibrary.Domain.Member")
                        .WithMany("Competitions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartLibrary.Domain.MemberIdentity", b =>
                {
                    b.HasOne("SmartLibrary.Domain.Member")
                        .WithOne("MemberIdentity")
                        .HasForeignKey("SmartLibrary.Domain.MemberIdentity", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
